### ISSUE TITLE
Theme: Check rtl layouts and styles.

### ISSUE THREAD

**Issue by kalpaitch** [warmshowers/Warmshowers.org#603]
Most of the initial layout and theme work has focused on the default layout flow. Once these are completed we need to check and implement changes where necessary for the rtl languages. Hoping the zen framework takes care of a large part of this by default.

**Comment by rfay** [comment]
Awesome language use. 

RTL does *not* have to be perfect. Mostly usable at deploy is good enough. It's only "mostly usable" now, the Persian version has some problems that I can't sort out very well because I don't grok any RTL at all, but especially not Persian.

But eventually we'll have Arabic I would imagine...

**Comment by rfay** [comment]
Closing this until we have a Farsi translator who can give us feedback.
