### ISSUE TITLE
Anon front page block assignment and finish work

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#673]
The anon front page is still pretty sketchy. I think mostly config is required, but it would be nice to have it in place sooner rather than later. 

It would be good to replace the center graphic, but I don't think that has to be done for this issue. For this issue we just need more-or-less parity, something to show to unregistered users that we won't be embarrassed about.

**Comment by kalpaitch** [comment]
https://github.com/warmshowers/Warmshowers.org/pull/758

**Comment by kalpaitch** [comment]
This is currently what it looks like on my local:
![screenshot from 2015-09-12 18 32 25](https://cloud.githubusercontent.com/assets/334114/9832882/c1ef9c9a-597c-11e5-9b95-0404ccc612f3.png)

Difference on staging seems to be:
1) block placement issues (possibly due to upgrade)
2) menu links in footer
3) language switcher doesn't use jquery plugin (bug in language_switcher module requires manual config)
@rfay possibly best to split these into separate tickets, but can discuss first.

**Comment by rfay** [comment]
Wow, that looks great. Now to make sure a drush fra makes it look that way :)

**Comment by rfay** [comment]
Assigned to @jeanfrancoisbeaulieu since Andrew is out this week. What we can do is just draw out a new page, build the blocks, get the placement for them going, and then style it.

**Comment by rfay** [comment]
Here's the plan that @jeanfrancoisbeaulieu and I talked about:

1. He will sketch out a simple new anon front page layout - just paper is fine, or whatever tool.
2. I will create content as necessary on the live site and implement the blocks that may be necessary.
3. I'll place the blocks, update features, and turn it over to him for styling.

**Comment by rfay** [comment]
This is awesome and done. @jeanfrancoisbeaulieu is working on a new anon front as well.
