### ISSUE TITLE
Get requests don't require CSRF validation

### ISSUE THREAD

**Issue by klzig** [warmshowers/Warmshowers.org#851]
The two get requests (/services/rest/user/<uid> and /user/<uid>/json_recommendations) return data normally even if the x-csrf-token header isn't supplied.

Probably expected but it surprised me a bit in testing so thought I'd report it.

**Comment by rfay** [comment]
That's super interesting, I wasn't aware. It does make sense though, since CSRF is not a threat on GET requests (that don't change anything). [CSRF attacks are specifically about state-change](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)), so a GET would not be a part of that.

Thanks so much for pointing this out. I certainly learned something today.
